[package]
name = "solana-program"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[client]
name = "client"
path = "client/main.rs"

[dependencies]
solana-program = "1.18"

[dev-dependencies]
solana-program-test = "1.18.26"
solana-sdk = "1.18.26"
tokio = "1.42.0"
