[package]
name = "solana-program-test"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "1.18.26"
solana-sdk = "1.18.26"
solana-program = "1.18.26"
tokio = "1.42.0"
lazy_static = "1.5.0"
dotenv = "0.15.0"
borsh = "1.5.3"
